/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include<stdlib.h>
#include<string.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ADC_BASE_ADDRESS 	0x40012400UL
#define ADC1_OFFSET 		0x04UL
#define ADC1_REG_ADDR 		(ADC_BASE_ADDRESS + ADC1_OFFSET)

#define RCC_BASE_ADDRESS    0x40021000UL
#define RCC_APB2ENR_OFFSET  0x18UL
#define RCC_APB2ENR        (RCC_BASE_ADDRESS + RCC_APB2ENR_OFFSET)


int main()
{
	// Turn on the clock
	uint32_t *pAPB2ADC_REG = (uint32_t*)RCC_APB2ENR;
	*pAPB2ADC_REG |= (1<<9);

	//Turn on scan of ADC1
	uint32_t  *pADC1_REG = (uint32_t*)(ADC1_REG_ADDR);
	*pADC1_REG |= (1<<8);

    for(;;);
}

