/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{
    uint32_t volatile *pClkRg = 	(uint32_t*)0x40021018; // APB2 EN NUCLEO STM32F103RB
    uint32_t volatile *pPortAMode = (uint32_t*)0x40010800; // ESTO PARA EL MODO DEL PUERTO A5
    uint32_t volatile *pPortAOut= 	(uint32_t*)0x4001080C; // ESTO PARA EL PUERTO A5
    uint32_t volatile *pPortBMode = (uint32_t*)0x40010C00; // ESTO PARA EL MODO DEL PUERTO B7
    uint32_t volatile *pPortBIn= 	(uint32_t*)0x40010C08; // ESTO PARA EL PUERTO B7

    //1.- Se parte a encender el GPIO CLOCK del Puerto A y B
    *pClkRg |= (1<<2);
    *pClkRg |= (1<<3);

    //2.- Se configura el modo del puerto a SALIDA para el PINA5
    *pPortAMode &=~ (15<<20);
    *pPortAMode |= (1<<20);

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//2.1 Se configura como entrada para el PINB7
	*pPortBMode &=~ (15<<28);
	*pPortBMode |= (1<<31);

	while(1)
	{
		uint8_t pinStatus = (uint8_t)(*pPortBIn & 0x80);

		if (!pinStatus)
		{
			//3.- Configurar como HIGH el pin5 en ODR
			*pPortAOut |= (1<<5);
		}
		else
		{
			*pPortAOut &=~ (1<<5);
		}
	// Se busca en IDR el registro de lectura y se aplica
	}
}


