/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif




int main(void)
{
    uint32_t *pClkRg = 		(uint32_t*)0x40021018; // APB2 EN NUCLEO STM32F103RB
    uint32_t *pPortAMode = 	(uint32_t*)0x40010800; // ESTO PARA EL MODO DEL PUERTO A5
    uint32_t *pPortAOut= 	(uint32_t*)0x4001080C; // ESTO PARA EL PUERTO A5

    // Se calcula de la siguiente forma la direccion de memoria del modo del puerto B
    // Memory map en reference manual, viene la base la cual es 0x4001 0C00
    // En GPIO Registers se encuentra el puerto B en GPIOx_CRL
    // Tiene un offset de 0x00 por lo cual la dirección de memoria es:
    // 0x4001 0C00 + 0x00   = 0x4001 0C00
    uint32_t *pPortBMode = 	(uint32_t*)0x40010C00; // ESTO PARA EL MODO DEL PUERTO B7
    // Nuevamente, se busca ahora para el pin de entrada en IDR el offset y se le agrega
    // Desde IDR el offset es de 0x08
    // 0x4001 0C00 + 0x08 = 0x4001 0C08
    uint32_t *pPortBIn= 	(uint32_t*)0x40010C08; // ESTO PARA EL PUERTO B7

    //1.- Se parte a encender el GPIO CLOCK del Puerto A
    // El puerto A se activa desde APB2, en el bit 2
    // El puerto B se activa desde APB2, en el bit 3

    *pClkRg |= (1<<2);
    *pClkRg |= (1<<3);

    //2.- Se configura el modo del puerto a SALIDA para el PINA5
    //Primero se limpian los elementos de CNF5 (22,23) y MODE5(20,21)
    //Se activa el bit para modo de salida 01 (20MHZ bit 21) y Tipo General (00 bit 22 23)

    *pPortAMode &=~ (15<<20);
    *pPortAMode |= (1<<20);

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
	//2.1 Se configura como entrada para el PINB7
	// En (GPIOx_CRL) el MODO y el CNF para el PINB7 se encuentran en 28,29,30,31
    // Se deja en 1000 debido a que es un INPUT
	*pPortBMode &=~ (15<<28);
	*pPortBMode |= (1<<31);

	while(1)
	{
		uint8_t pinStatus = (uint8_t)(*pPortBIn & 0x80);

		if (!pinStatus)
		{
			//3.- Configurar como HIGH el pin5 en ODR
			*pPortAOut |= (1<<5);
		}
		else
		{
			*pPortAOut &=~ (1<<5);
		}
	// Se busca en IDR el registro de lectura y se aplica
	}
}


